cursor #e0e3de
cursor_text_color #bfc9bf

foreground            #e0e3de
background            #101411
selection_foreground  #1d3526
selection_background  #b1ceb8
url_color             #8fd6a8

color0   #101411
color1   #f6946e
color2   #6bd66c
color3   #fff172
color4   #7acb96
color5   #26633c
color6   #8fd6a8
color7   #d3e0d8
color8   #808b84
color9   #ffba9f
color10  #a5ffa7
color11  #fff6a5
color12  #a9ebc0
color13  #c3ffd8
color14  #d8ffe6
color15  #f8fffa
